# Generated by Django 4.0.3 on 2022-12-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='checking',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
