apiVersion: v1
kind: ConfigMap
metadata:
  namespace: pybo
  name: pybo-mydb-config
  labels:
    app: pybo-mydb
data:
  master.cnf: |
    [mysqld]
    log-bin
  slave.cnf: |
    [mysqld]
    super-read-only
