apiVersion: v1
kind: Service
metadata:
  namespace: pybo
  name: pybo-mydb-read
  labels:
    app: pybo-mydb
spec:
  ports:
  - name: pybo-mysql
    port: 3306
    targetPort: 3306
  selector:
    app: pybo-mydb
  type: ClusterIP