kind: PersistentVolume
apiVersion: v1
metadata:
  name: web-pv
  labels:
    app: web
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/intern/yaml/db"
